### ISSUE TITLE
Write acceptance tests

### ISSUE THREAD

**Issue by i4ki** [NeowayLabs/dchan#6]
Write acceptance tests for API documented here:
https://github.com/NeowayLabs/dchan/blob/master/docs/api.org

**Comment by katcipis** [comment]
It would be nice if you could explain a little more what would be these tests :-)

**Comment by i4ki** [comment]
:-)

Thanks for asking!

I'd described an API, CSP semantics and desired goals of the solution here: https://github.com/NeowayLabs/dchan/blob/master/docs/api.org
I'll use that as contract for development.

The idea is write tests to make sure everything will work as expected/documented.
